### ISSUE TITLE
Please allow setting colors for plots

### ISSUE THREAD

**Issue by vladimirg** [Erik-White/ScanLag#53]
Often it makes sense for curves in e.g. growth_curve.png to be color-coded (e.g., if there are 3 technical replicas in a 6-plate lattice, it would make sense to assign each pair of replicas their own color). Perhaps allow for a configuration file to specify the plate parameters (lattice, labels, colors, etc.).

**Comment by Erik-White** [comment]
I considered this, but decided against adding configuration file input - at least for the time being. The plots are only meant to be indicative and give a quick overview of the data. I would expect the vast majority of users would want to do their own stats and plots, instead of reusing the plots from ColonyScanalyser.

**Comment by vladimirg** [comment]
I agree that many users would like to do their own plots, but a birds-eye view of the growth and appearance data is a major selling point. Right now everything is too similar, and users are almost forced to create their own plots right away, even though the current ones are excellent for a preliminary overview (with the colors being the only impediment). I urge you to reconsider.
