### ISSUE TITLE
Erroneous trend curves in growth_curve.png for a single plate

### ISSUE THREAD

**Issue by vladimirg** [Erik-White/ScanLag#54]
See below:

![growth_curve](https://user-images.githubusercontent.com/1148887/83408788-ecac2b80-a41b-11ea-90b8-45b03bb1b320.png)

These are the data for that plate:
[Archive.zip](https://github.com/Erik-White/ColonyScanalyser/files/4711225/Archive.zip)

**Comment by Erik-White** [comment]
That is a strange curve! Something has definitely gone wrong at 39 and 46 hours. The way the data has all shifted at the same time point suggests that one of the images may be out of order somehow. Something similar may have happened around 22 hours as well.

Could you upload the images to Dropbox so I can take a look?

**Comment by vladimirg** [comment]
The images are at `Berman Lab Staff Files/Alona/Scanner0`. This problem only occurs in this plate (plate 3); the other plates seem OK.

**Comment by Erik-White** [comment]
Thanks, I'll have a look

**Comment by Erik-White** [comment]
I think this was an image alignment issue, and is now fixed with the new image alignment features in v0.6. I ran the images with `--image-align verify`, and now I now get a good curve:

![growth_curve](https://user-images.githubusercontent.com/26148654/105755190-3ddcd280-5f4b-11eb-805a-b24ea5a4259d.png)
