### ISSUE TITLE
2  plates analysis are missing 

### ISSUE THREAD

**Issue by AlonaDeRusso** [Erik-White/ScanLag#68]
![image](https://user-images.githubusercontent.com/66908246/84801383-c4215580-b007-11ea-9294-75549c1ded96.png)

 Plates 3 and 4 were not analyzed.

Plate Number: 3+4
Location in Dropbox: Berman Lab/Berman Lab Staff Files /Alona/ScanLag 28.5.20/HallScanner0
Version: 0.4.4

**Comment by Erik-White** [comment]
That is unusual! Did you run the analysis with [different command line arguments](https://erik-white.github.io/ColonyScanalyser/command_line_arguments/)?

Specifically the `--plate-size` and `--plate-lattice` arguments will affect how plates are detected.

Note that the arguments will be slightly different since you're using version 0.4.4. I recommend upgrading to the latest version:
`pip3 install colonyscanalyser --upgrade`

**Comment by AlonaDeRusso** [comment]
I only used this argument: --plate_labels

**Comment by Erik-White** [comment]
Hi Alona this should now be fixed if you upgrade to the latest version (0.5.2):
`pip3 install colonyscanalyser --upgrade`

I tested it with your images and the plates were correctly identified.
