### ISSUE TITLE
Colonies are not detected

### ISSUE THREAD

**Issue by achiarel** [Erik-White/ScanLag#73]
Hi Erik,
I am using the version ColonyScanlayser 0.5.2 but I still have a problem with unrecognized colonies and this can affect the analysis. Is it possible to change the colony filtering parameters? Here you can find an example (the white arrow indicating the colony which I really don't understand why is not detected)
[Example.pptx](https://github.com/Erik-White/ColonyScanalyser/files/5291133/Example.pptx)

Thanks in advance for your reply, it would be extremely helpful!!

Adriana

**Comment by Erik-White** [comment]
Hi, it is a little difficult to understand what has happened just with the final image. Generally all of the 'objects' in the plate will be identified but not all of the visible objects on a plate will be colonies. In order to filter out static objects and noise the [filtering criteria](https://erik-white.github.io/ColonyScanalyser/colony_filtering/) are applied.

Since the rest of the colonies appear to have been correctly identified, I would guess that there was some piece of debris in the spot that the colony was growing. If there is debris in plate (e.g. dust of a bubble in the agar) it makes it difficult to accurately measure colony area, so these colonies are excluded from measurement. This may be why the colony next to #79 has also been filtered out.

There is currently no command line argument to adjust the filtering, but it is something that I would like to add eventually. I would also like to explicitly indicate colonies that have been identified but excluded based on filtering criteria. I am unfortunately very busy at the moment but would welcome any pull requests.

**Comment by achiarel** [comment]
Hi, thanks for your reply.

Indeed, what could have happened is that, according the to filtering criteria, undetected colonies were too big since the beginning (**Colonies with large initial areas (merged colonies) won't be detected**).

So I guess you have a script for filtering, is that accessible or not? 
I am using a lot ScanLag for my PhD thesis and I found your pipeline much more user-friendly than the one from the authors of the system, at least because I can also easily extrapolate data compared to what Matlab generates. I would like to discuss with you more in detail about it, if you are up for it.


Adriana

**Comment by Erik-White** [comment]
The issue may have been that the plates were moved slightly at some point during the run and therefore the colonies do not all line up perfectly in the images.

I have added new image alignment and data smoothing functionality to the package. Please try updating to the latest version and re-running the images. You may need to use `--image-align verify` (the default is `quick`) and play around with the `--image-align-tolerance` value.
